// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpgefrjmqmwyygkfyrrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwZ2VmcmptcW13eXlna2Z5cnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzk2MDYsImV4cCI6MjA2Mzk1NTYwNn0.Z6dpykBixtABo-smYyikeXdT2zOJmnDGlmYTrdp0cPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);